import type { JudgeSnapshot } from '../../src/agent/judge.js';

export function fixture(timestamp = 1_800_000_000_000): JudgeSnapshot {
  const snapshot: JudgeSnapshot = {
    timestamp,
    functional: {
      timestamp,
      state: 'LIVE',
      mcpHealthy: true,
      symbols: ['BTC-USDT', 'ETH-USDT'],
      markets: {
        'BTC-USDT': {
          close: 63000,
          spreadBps: 2.1,
          atrPctPercentile: 0.52,
          regime: 'TRENDING_UP',
          candidateAction: 'BUY',
          oqs: 78,
          edgeCostRatio: 2.4,
          setupType: 'TREND_PULLBACK',
          obiTop5: 0.15,
          micropriceLeanBps: 0.9,
          dataAgeMs: 120,
        },
        'ETH-USDT': {
          close: 3400,
          spreadBps: 1.8,
          atrPctPercentile: 0.4,
          regime: 'RANGE',
          candidateAction: 'HOLD',
          oqs: 66,
          edgeCostRatio: 1.7,
          setupType: 'RANGE_REVERSION',
          obiTop5: -0.05,
          micropriceLeanBps: -0.2,
          dataAgeMs: 140,
        },
      },
      selectedSymbol: 'BTC-USDT',
      selectedOQS: 78,
      llm: { status: 'VALID', action: 'AGREE', riskFlag: 'NONE' },
      riskCertificate: {
        requestedSymbol: 'BTC-USDT',
        existingOpenPositionSymbols: [],
        gates: [
          {
            name: 'CONFIG_VALID',
            status: 'PASS',
            reason: 'Valid configuration',
          },
          { name: 'SPREAD', status: 'FAIL', reason: 'Spread too wide' },
        ],
        verdict: 'REJECT',
        riskMode: 'NORMAL',
        calculatedNotional: null,
        protectionPlan: null,
      },
      openPositionSymbol: null,
      position: null,
      equity: {
        starting: 10000,
        current: 10120,
        peak: 10150,
        dailyPnl: 120,
        dailyReturnPct: 1.2,
        currentDrawdownPct: 0.3,
        maximumDrawdownPct: 0.6,
      },
      riskMode: 'NORMAL',
      degradedReason: null,
    },
    reasoning: {
      selectedSymbol: 'BTC-USDT',
      perSymbolOqs: { 'BTC-USDT': 78, 'ETH-USDT': 66 },
      criticVerdict: 'AGREE',
      counterThesis:
        'ETH microstructure is weakening and broad-market confirmation is limited.',
      riskCertificate: null,
    },
    atk: {
      readLane: {
        status: 'READY',
        serverVersion: '1.2.3',
        profile: 'demo',
        readOnly: true,
        toolCount: 8,
      },
      writeLane: {
        status: 'READY',
        serverVersion: '1.2.3',
        profile: 'demo',
        tools: ['spot_place_order'],
      },
      uniqueToolsUsed: ['market_get_ticker'],
      recentTraces: [
        {
          timestamp,
          lane: 'READ',
          toolName: 'market_get_ticker',
          purpose: 'Latest price',
          symbol: 'BTC-USDT',
          profile: 'demo',
          latencyMs: 41,
          success: true,
          errorCode: null,
          errorMessage: null,
          cycleId: 'c1',
          decisionId: null,
        },
      ],
      latestProvenance: {
        cycleId: 'c1',
        timestamp,
        selectedSymbol: 'BTC-USDT',
        result: 'REJECTED',
        nodes: [
          {
            source: 'ATK_MCP',
            lane: 'READ',
            toolName: 'market_get_ticker',
            symbol: 'BTC-USDT',
            timestamp,
            description: 'Latest price',
            latencyMs: 41,
            success: true,
            result: 'OK',
          },
          {
            source: 'LOCAL',
            lane: null,
            toolName: null,
            symbol: 'BTC-USDT',
            timestamp,
            description: 'Features, regime and opportunity score',
            latencyMs: null,
            success: true,
            result: '78',
          },
          {
            source: 'LOCAL',
            lane: null,
            toolName: null,
            symbol: 'BTC-USDT',
            timestamp,
            description: 'Deterministic cross-symbol ranking',
            latencyMs: null,
            success: true,
            result: 'BTC-USDT',
          },
          {
            source: 'LLM',
            lane: null,
            toolName: null,
            symbol: 'BTC-USDT',
            timestamp,
            description: 'Market Critic reviewed selected candidate',
            latencyMs: null,
            success: true,
            result: 'AGREE',
          },
          {
            source: 'RISK',
            lane: null,
            toolName: null,
            symbol: 'BTC-USDT',
            timestamp,
            description: 'Deterministic Risk Certificate',
            latencyMs: null,
            success: true,
            result: 'REJECT',
          },
        ],
        summary: {
          symbol: 'BTC-USDT',
          setupType: 'TREND_PULLBACK',
          oqs: 78,
          selection: 'SELECTED',
          criticVerdict: 'AGREE',
          counterThesis: 'ETH microstructure is weakening.',
          riskResult: 'REJECT',
          primaryRejectionReason: 'Spread too wide',
          executionResult: null,
          outcomeR: null,
          pnl: null,
        },
      },
      recentDecisions: [],
      recentDecisionMemory: [],
      indicatorCrossChecks: [
        {
          symbol: 'BTC-USDT',
          indicator: 'EMA9',
          localValue: 2,
          atkValue: 2,
          difference: 0,
          status: 'MATCH',
        },
      ],
      crossMarket: {
        symbols: ['BTC-USDT', 'ETH-USDT'],
        status: 'AVAILABLE',
        spread: 0.1,
        timestamp,
      },
      contextPulse: {
        timestamp,
        newsShock: 'NONE',
        sentiment: 'NEUTRAL',
        macroEventSoon: false,
      },
    },
    safety: {
      liveArmed: false,
      riskMode: 'NORMAL',
      protectionMode: null,
      reconciliationPending: false,
      degradedReason: null,
    },
  };
  snapshot.reasoning.riskCertificate = snapshot.functional.riskCertificate;
  return snapshot;
}
